---
- name: Clean kolibri dir if it exists
  file:
    state: absent
    path: '{{ kolibri_dev_dir }}'

- name: Get kolibri code
  shell: cd ~ && git clone {{ kolibri_git_repository }}

- name: Initialize kolibri virtualenv
  shell: virtualenv --python=python3.6 {{ kolibri_venv_dir }}

- name: Install kolibri pip requirements
  pip: requirements={{ kolibri_dev_dir }}/requirements.txt virtualenv={{ kolibri_venv_dir }}

- name: Install kolibri dev requirements
  pip: requirements={{ kolibri_dev_dir }}/requirements/dev.txt virtualenv={{ kolibri_venv_dir }}

- name: Install kolibri python package in 'editable' mode
  shell: cd {{ kolibri_dev_dir }} && . {{ kolibri_venv_dir }}/bin/activate && pip install -e .

- name: Install js dependencies - yarn install
  shell: cd {{ kolibri_dev_dir }} && . {{ kolibri_venv_dir }}/bin/activate && yarn install

- name: Install js dependencies - yarn run build
  shell: cd {{ kolibri_dev_dir }} && . {{ kolibri_venv_dir }}/bin/activate && yarn run build
