---
- name: Update apt
  shell: apt clean

- name: Update apt
  shell: apt update

- name: Install build-essential
  apt: pkg=build-essential state=latest

- name: Install libpq-dev
  apt: pkg=libpq-dev state=latest

- name: Install python3-dev
  apt: pkg=python3-dev state=latest

- name: Install python-dev
  apt: pkg=python-dev state=latest

- name: Install python3.6
  shell: |
    add-apt-repository ppa:jonathonf/python-3.6 -y
    apt-get update
    apt-get install python3.6 -y

- name: Install unzip
  apt: pkg=unzip state=latest

- name: Install npm
  apt: pkg=npm state=latest

- name: Upgrade node
  shell: |
    npm cache clean -f
    npm install -g n
    n 6

- name: Configure the package repository and install yarn
  shell: |
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
    echo 'deb https://dl.yarnpkg.com/debian/ stable main' | tee /etc/apt/sources.list.d/yarn.list
    apt update
    apt install yarn -y
